### ISSUE TITLE
Establish basis of Echidna integration

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-contracts#473]
[Echidna](https://github.com/trailofbits/echidna) is a weird creature that eats bugs and is highly electrosensitive. More seriously, Echidna is a Haskell library designed for fuzzing/property-based testing of EVM code. It supports relatively sophisticated grammar-based fuzzing campaigns to falsify a variety of predicates.
As a recommendation from Trail of Bits, Echidna should be run from within a docker container.

Find out how to write scripts that run Echidna.
All security related scripts should go into a directory "security".
This ticket should create a basic script that does a simple check.

Add Echidna as part of the Travis CI build, utilizing the Echidna docker image, so that the Echidna  script is run as part of the build process.

[Trail of Bits on Docker Hub](https://hub.docker.com/u/trailofbits/)

**Comment by schemar** [comment]
⚠️**Note:** Do **not** add Echidna to TravisCI!

**Comment by schemar** [comment]
Have a look at https://github.com/trailofbits/etheno !

**Comment by sarvesh-ost** [comment]
Setup is documented here 
https://github.com/sarvesh-ost/mosaic-contracts/tree/echidna_security
