### ISSUE TITLE
Move organization contracts into npm

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-contracts#538]
Use `npm` to load the organization contracts, so that they are re-usable from a single source.
Help: https://truffleframework.com/docs/truffle/getting-started/package-management-via-npm

### Before publishing

When using a network like the default develop network that's configured to match any Ethereum client (like Ganache or Truffle Develop), you're bound to have network artifacts lying around that you don't want published. Before publishing your package, consider running the following command to remove any extraneous network artifacts:

```
$ truffle networks --clean
```

**Comment by hobofan** [comment]
I would propose to instead use NPM for the package management: https://truffleframework.com/docs/truffle/getting-started/package-management-via-npm

**Comment by schemar** [comment]
Thanks @hobofan I updated the ticket.

**Comment by hobofan** [comment]
Is this solved by #619 ?

**Comment by schemar** [comment]
No. This ticket is about the solidity source code of the organization.
