### ISSUE TITLE
Don't expose EIP20Token in npm package

### ISSUE THREAD

**Issue by hobofan** [OpenST/mosaic-contracts#629]
The `EIP20Token` the is currently exposed in the NPM package is not what one would normally expect from an `EIP20Token`, where you can define the supply, etc., but it actually serves as a base contract that is inherited by `OSTPrime`.

This can be very confusing, as this can lead to the assumption that `EIP20Token` is a simple EIP20 token that can be used for the `tokenAddress` and `baseTokenAddress` params of `Gateway`.  In fact `EIP20Token` has a fixed supply of 0 and is useless when deployed directly.

Because of this `EIP20Token` should be exposed as `EIP20TokenInterface` and should only include the ABI, not the BIN.

Please make sure the ABI is exactly what a consumer would expect.

**Comment by schemar** [comment]
That's done in #636
