### ISSUE TITLE
register OST in MetaMask

### ISSUE THREAD

**Issue by benjaminbollen** [OpenST/mosaic-contracts#682]
Make PR to add OST support on mainnet (and Ropsten if possible) for OST in Metamask

https://metamask.github.io/metamask-docs/Main_Concepts/Best_Practices/Registering_Your_Token

icon for OST :

![Icon.svg](https://images.zenhubusercontent.com/577fc702bf93871ccd9dbf5c/0585f444-d4bb-48ee-8055-824908f4f161)

**Comment by schemar** [comment]
There are two options:

1. Create a page and/or a link that users click in order to add OST to their MetaMask (according to [EIP747](https://github.com/estebanmino/EIPs/blob/master/EIPS/eip-747.md).
2. Register a token in MetaMask's [official meta-data repository](https://github.com/MetaMask/eth-contract-metadata).

I will try option 2, even though MetaMask discourages that due to the overhead on their side.

**Comment by schemar** [comment]
Note: in the meantime there is a very easy way to add the token to your MetaMask:

1. Go to the [etherscan ST page](https://etherscan.io/token/0x2c4e8f2d746113d0696ce89b35f0d8bf88e0aeca)
2. Click the three dots in the upper right ![image.png](https://images.zenhubusercontent.com/5baa2e199e33b023868f33d9/26fa834b-11e5-4abc-929d-ae8a2a8bf15d)
3. Click on "Add Token to Web3 Wallet"

**Comment by schemar** [comment]
I'll create a follow-up ticket for option 1 (EIP747).

**Comment by schemar** [comment]
~I'll create a follow-up ticket for option 1 (EIP747).~
I forwarded the info to @sisco128 / @siscolo128

**Comment by schemar** [comment]
Created PR on the MetaMask repo: https://github.com/MetaMask/eth-contract-metadata/pull/272

**Comment by schemar** [comment]
Created PR in the [MetaMask repository](https://github.com/MetaMask/eth-contract-metadata/pull/272)

**Comment by abhayks1** [comment]
Reviewing this ticket

**Comment by abhayks1** [comment]
LGTM 👍 
One question, After the metamask PR is merged front end needs to integrate below code to suggest OST token to user. right?
https://metamask.github.io/metamask-docs/Main_Concepts/Best_Practices/Registering_Your_Token#example

**Comment by schemar** [comment]
That would be the *alternative* to adding the token to the "Default Token List" (which we want to achieve).

**Comment by abhayks1** [comment]
ok thanks.

**Comment by schemar** [comment]
Was merged by MetaMask 🚀
