### ISSUE TITLE
Remove value token from EIP20CoGateway

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-contracts#692]
* Check that the value token is really not used in the EIP20CoGateway (check also dependencies, libraries, and callers).
* If it is not used, remove it from the EIP20CoGateway.

**Comment by benjaminbollen** [comment]
breaks interface; note consideration for star gateway https://app.zenhub.com/workspaces/-l3-5c6ac34d5977bf432a79b94d/issues/openst/mosaic-contracts/720
