### ISSUE TITLE
Stake and redeem should not have a nonce parameter

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-contracts#694]
Remove the nonce parameter from EIP20 Gateway `stake` and EIP20CoGateway `redeem` methods. Instead, use the calculated expected nonce. It will be validated by comparing the message hashes.

**Comment by benjaminbollen** [comment]
valid, but breaks interface, note for star gateway https://app.zenhub.com/workspaces/-l3-5c6ac34d5977bf432a79b94d/issues/openst/mosaic-contracts/720
