### ISSUE TITLE
token should be called valueToken where applicable

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-contracts#701]
Use valueToken instead of token accross contracts (OSTPrime, UtilityToken, EIP20CoGateway, EIP20Gateway and SimpleStake).

Example: https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/gateway/UtilityToken.sol#L79

**Comment by benjaminbollen** [comment]
does this break interfaces, or only improve the readability (by using consistent names)?

**Comment by jasonklein** [comment]
> does this break interfaces, or only improve the readability (by using consistent names)?

(as discussed and agreed elsewhere) Yes, this does break interfaces (e.g., `EIP20Gateway.token()` --> `EIP20Gateway.valueToken()`); getters will be added to fix the breaks.
