### ISSUE TITLE
messageStatus should be called inboxMessageStatus

### ISSUE THREAD

**Issue by schemar** [OpenST/mosaic-contracts#703]
https://github.com/OpenSTFoundation/mosaic-contracts/blob/fa436b06cacf3ea84d72550b7398f94220476648/contracts/lib/MessageBus.sol#L256

**Comment by sarvesh-ost** [comment]
This change was already done in another ticket. `_messageStatus` is updated to `_inboxMessageStatus` and `_outboxMessageStatus`. 


https://github.com/OpenST/mosaic-contracts/blob/6714a938dba15a7eac59fa0108757f2671f77f11/contracts/lib/MessageBus.sol#L245

https://github.com/OpenST/mosaic-contracts/blob/6714a938dba15a7eac59fa0108757f2671f77f11/contracts/lib/MessageBus.sol#L359

https://github.com/OpenST/mosaic-contracts/blob/6714a938dba15a7eac59fa0108757f2671f77f11/contracts/lib/MessageBus.sol#L510

**Comment by schemar** [comment]
OK. Next time you can also close the issue 😀
