### ISSUE TITLE
Generate extensive data set using MPP fuzzer for unit test

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/mosaic-contracts#718]
Using the MPP fuzzer generate the extensive dataset which covers many cases to unit test Merkel Patricia Proof library. 

Sample cases: 
1. Full-length proof with all branch nodes. 
2. Proof with one extension node and all branch nodes. 
3. Proof with more than one extension node. (e,b,e,b,l) 
 
Write a script: 
 1.  which can be executed to generate test dataset using MPP fuzzer. 
 2. Which can write generated test dataset into a json file.

**Comment by schemar** [comment]
1. Figure out what relevant test branches are.
2. Generate relevant test branches and commit the generated data.

**Comment by schemar** [comment]
No more than 100 test cases

**Comment by schemar** [comment]
* all branch nodes
* all extension nodes
* one extension node and multiple branch nodes
* one branch node and multiple extension nodes
* multiple branch nodes and multiple extension nodes

* should end on `l`
* should end on `b`

* should be very short
* should be very long

**Comment by schemar** [comment]
huhu

**Comment by schemar** [comment]
Moving to parking lot, waiting for #716 to be finished and ready. There are still some uncertainties:
* why does the fuzzy generator require path and value as input?
* what pattern/path/value combinations produce a working output?

Currently, I get the following error for all inputs:
```
tools/fuzzy_proof_generator_tool/FuzzyProofGenerator.ts:39
    assert(Util.assertNibbleArray(nibblePath));
    ^
AssertionError [ERR_ASSERTION]: undefined == true
    at Object.generate (/tools/fuzzy_proof_generator_tool/FuzzyProofGenerator.ts:39:5)
```
