### ISSUE TITLE
Make comment about location of message box more general in GatewayBase.sol

### ISSUE THREAD

**Issue by sarvesh-ost** [OpenST/mosaic-contracts#725]
https://github.com/OpenST/mosaic-contracts/blob/76fffcf556a9b7a26bce89e29410358cfd251da5/contracts/gateway/GatewayBase.sol#L115

Currently, comment specifies fixed `location 1`, but the current correct location is `7`.  Make comment more general to avoid this kind of misalignment.

**Comment by schemar** [comment]
Already done by @deepesh-kn in 159a25bfd

**Comment by schemar** [comment]
Specific line: https://github.com/OpenST/mosaic-contracts/commit/159a25bfdcfefa9d5dab918bbfe336ac9203a8fd#diff-8019a7900cc365182c48711243c6d879R116
