### ISSUE TITLE
Use actual staker proxy contract in OST' composer contact

### ISSUE THREAD

**Issue by deepesh-kn** [OpenST/mosaic-contracts#742]
- Composer contract will be developed with mock staker proxy contract.
- Staker contract will be developed simultaneously.

This ticket is about using staker proxy contract in composer contract.

**Comment by schemar** [comment]
@deepesh-kn added #740 and #741 as blockers. What do you think?

**Comment by schemar** [comment]
#739 introduced a `ComposerInterface` to be able to call `removeStakerProxy()`.

Either make `Composer` implement the interface, or change `StakerProxy` to use the actual `Composer` and delete the `ComposerInterface`.

**Comment by deepesh-kn** [comment]
Closing this ticket as it is now already handled in https://github.com/OpenST/mosaic-contracts/pull/750
