### ISSUE TITLE
Upgrade truffle package to 5.0.19

### ISSUE THREAD

**Issue by gulshanvasnani** [OpenST/mosaic-contracts#758]
| Repo  | Current Version|
| ------------- | ------------- |
| Mosaic-Contracts  | beta  |
| Openst-contracts  | 5.0.10  |
| Branded-contracts  | 5.0.1  |
| Utilitytoken-contracts  | 5.0.1  |

**Comment by benjaminbollen** [comment]
the PR for mosaic-contracts requires more work apparently when updating truffle. We can open a new ticket for updating truffle in mosaic-contracts specifically?

**Comment by deepesh-kn** [comment]
> the PR for mosaic-contracts requires more work apparently when updating truffle. We can open a new ticket for updating truffle in mosaic-contracts specifically?

It is now fixed.
