### ISSUE TITLE
Remove a check for a valid nonce and mutex from StakerProxy.stake()

### ISSUE THREAD

**Issue by pgev** [OpenST/mosaic-contracts#763]
- **Remove a check for a valid nonce from StakerProxy.stake()**

In the context of OSTComposer functionality, we've already checked the validity of a provided nonce within OSTComposer::requestStake() function (to make sure that OSTComposer::acceptStakeRequest() would not fail because of an invalid nonce).

In the context of StakerProxy::stake() function this check is not needed as a call to gateway stack function would assure this.

- **Replace StakerProxy's own implementation of a mutex by inheriting from Mutex contract.**
- **Remove mutex from OSTComposer::acceptStakeRequest function.**

We can safely remove a mutex from OSTComposer::acceptStakeRequest and execute the following statements after the first require statement in the function:

```solidity
delete stakeRequestHashes[stakeRequest.staker][address(stakeRequest.gateway)];
delete stakeRequests[_stakeRequestHash];
```

- **Remove mutex from OSTComposer::revokeStakeRequest and OSTComposer::rejectStakeRequest**

We can safely remove mutex from `OSTComposer::revokeStakeRequest` and `OSTComposer::rejectStakeRequest` as the following statements in function `OSTComposer::removeStakeRequest` (called within above-mentioned functions) protects against reentrancy:

```solidity
        delete stakeRequestHashes[staker][address(stakeRequest.gateway)];
        delete stakeRequests[_stakeRequestHash];
```

**Comment by abhayks1** [comment]
Started working on it :rocket
