### ISSUE TITLE
Check an existence of an active stake request against gateway

### ISSUE THREAD

**Issue by pgev** [OpenST/mosaic-contracts#766]
The following `assert` from `OSTComposer::requestStake`

```solidity
require(
    stakeRequestHashes[msg.sender][address(_gateway)] == bytes32(0),
    "Request for this staker at this gateway is already in process."
);
```

should be replaced by checking an active stake request existence for the current staker from `_gateway` input of `OSTComposer::requestStake`.

A proposal is to introduce a new external function within gateway that returns boolean wrt existence of an active stake request for the passed staker address.

**Comment by benjaminbollen** [comment]
`stakeRequest` is different state from ongoing `stakes` in gateway
