### ISSUE TITLE
Remove mutex from OSTComposer::acceptStakeRequest function

### ISSUE THREAD

**Issue by pgev** [OpenST/mosaic-contracts#767]
We can safely remove a mutex from OSTComposer::acceptStakeRequest and execute the following statements after the first require statement in the function:

```solidity
delete stakeRequestHashes[stakeRequest.staker][address(stakeRequest.gateway)];
delete stakeRequests[_stakeRequestHash];
```

**Comment by deepesh-kn** [comment]
This will be handled in this ticket.https://github.com/openst/mosaic-contracts/issues/763
