### ISSUE TITLE
Remove mutex from OSTComposer::revokeStakeRequest and OSTComposer::rejectStakeRequest

### ISSUE THREAD

**Issue by pgev** [OpenST/mosaic-contracts#768]
We can safely remove mutex from `OSTComposer::revokeStakeRequest` and `OSTComposer::rejectStakeRequest` as the following statements in function `OSTComposer::removeStakeRequest` (called within above-mentioned functions) protects against reentrancy:

```solidity
        delete stakeRequestHashes[staker][address(stakeRequest.gateway)];
        delete stakeRequests[_stakeRequestHash];
```

**Comment by deepesh-kn** [comment]
This will be handled in this ticket.https://github.com/openst/mosaic-contracts/issues/763
